import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });
import { useState } from "react";

export default function PageRouter() {
  const [state, setState] = useState(0);

  const handleStateChange = () => {
    setState((prev) => prev + 1);
  };

  console.log("Renderizando...");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Page Router</h1>
      <p>Não posso rodar sem javascripto :( {state}</p>
      <button type="button" onClick={handleStateChange}>
        Mudar estado
      </button>
    </>
  );
}
